# Generated by Django 3.2.9 on 2022-01-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название обзора')),
                ('video_user', models.CharField(max_length=150, verbose_name='Автор обзора')),
                ('video', models.TextField(verbose_name='Видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_premier', models.DateField(verbose_name='Дата выхода обзора')),
                ('poster', models.ImageField(upload_to='preview/', verbose_name='Превью')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('category', models.ManyToManyField(related_name='review_category', to='reviews_ali.Category', verbose_name='Категории видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название новости')),
                ('less_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Новость')),
                ('date', models.DateField(verbose_name='Дата выхода новости')),
                ('image', models.ImageField(upload_to='image_news/', verbose_name='Превью новости')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('category_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_category', to='reviews_ali.category', verbose_name='Категории новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
