# Generated by Django 3.2.9 on 2022-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ali', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='image')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
